version: "3.8"

services:
  api01: &api
    build:
      context: .
    container_name: api-rinha-go-01
    hostname: api01
    environment:
      - ENVIRONMENT=local
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - DB_SSL_MODE=disable
      - DB_NAME=rinha
      - PORT=3000
      - LOG_LEVEL=info
      - DB_POOL_MINIMUM=6
      - DB_POOL_MAXIMUM=6
    restart: on-failure
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "75MB"
  api02:
    <<: *api
    container_name: api-rinha-go-02
    hostname: api02

  nginx:
    image: nginx:latest
    container_name: nginx-rinha-go
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

  postgres:
    image: postgres:alpine
    container_name: postgres-rinha-go
    hostname: postgres
    command: postgres -c 'log_error_verbosity=terse' -c 'log_min_error_statement=PANIC' -c 'log_min_messages=PANIC'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "350MB"
